version: '3.7'

volumes:
  root_node_modules:
    driver_opts:
      type: none
      o: bind
      device: $PWD/node_modules
  crawler_node_modules:
    driver_opts:
      type: none
      o: bind
      device: $PWD/apps/crawler/node_modules
  web_node_modules:
    driver_opts:
      type: none
      o: bind
      device: $PWD/apps/web/node_modules
  functions_node_modules:
    driver_opts:
      type: none
      o: bind
      device: $PWD/apps/functions/node_modules
services:
  app: &base
    build: .
    tty: true
    env_file: .env
    working_dir: /home/node/ageage-db
    volumes:
      - ./:/home/node/ageage-db
      - root_node_modules:/home/node/ageage-db/node_modules
      - crawler_node_modules:/home/node/ageage-db/apps/crawler/node_modules
      - web_node_modules:/home/node/ageage-db/apps/web/node_modules
      - functions_node_modules:/home/node/ageage-db/apps/functions/node_modules
  web:
    <<: *base
    command: 'yarn start'
    working_dir:  /home/node/ageage-db/apps/web
    ports:
      - 3000:3000
  crawler:
    <<: *base
    working_dir: /home/node/ageage-db/apps/crawler
    command: 'yarn dev:watch'
    ports:
      - 9229:9229
  functions:
    <<: *base
    working_dir: /home/node/ageage-db/apps/functions
    command: "yarn serve"
    ports:
      - 5000:5000
